### ISSUE TITLE
树莓派3b+刷的openwrt，安装过程报错

### ISSUE THREAD

**Issue by gaoyuke** [linkease/ddnsto-openwrt#6]
![1](https://user-images.githubusercontent.com/31268133/109598942-44b3c200-7b55-11eb-8d19-2646c8e630aa.png)
![2](https://user-images.githubusercontent.com/31268133/109598948-467d8580-7b55-11eb-9e87-88f80406d614.png)

**Comment by jannson** [comment]
我看看哈。

**Comment by gaoyuke** [comment]
koolshare的文件服务器 文件没有版本号后缀，你的脚本里加了后缀，导致无法下载文件。

**Comment by jannson** [comment]
感谢，已经修复。
