### ISSUE TITLE
make menuconfig无法找到ddnsto

### ISSUE THREAD

**Issue by bleach1991** [linkease/ddnsto-openwrt#7]
lean的源码
![image](https://user-images.githubusercontent.com/47608286/109608210-7d0ecc80-7b64-11eb-980e-a1fc8a06faf1.png)
源码添加进去后能搜索到，但是就是没有选项可以选
![image](https://user-images.githubusercontent.com/47608286/109608313-a4fe3000-7b64-11eb-961e-ea865d4c3a4c.png)

**Comment by jannson** [comment]
我看看哈，方法：

1. 先在 network 里面选择 ddnsto
2. 然后在 luci 里面再选择 ddnsto

你试试

**Comment by LeanFly** [comment]
> 我看看哈，方法：
> 
> 1. 先在 network 里面选择 ddnsto
> 2. 然后在 luci 里面再选择 ddnsto
> 
> 你试试

make menuconfig network 下没有看到ddnsto……

**Comment by Itxiaoniao** [comment]
make menuconfig

   Network  --->  
   Web Servers/Proxies  ---> 
 <*> ddnsto....................................... DDNS.to - the reverse proxy 


   LuCI  --->   
   3. Applications  --->
<*> luci-app-ddnsto.................................. LuCI support for ddnsto

**Comment by LeanFly** [comment]
> make menuconfig
> 
> Network --->
> Web Servers/Proxies --->
> <*> ddnsto....................................... DDNS.to - the reverse proxy
> 
> LuCI --->
> 3. Applications --->
> <*> luci-app-ddnsto.................................. LuCI support for ddnsto

多谢指正，已解决

**Comment by myvmiao** [comment]
直接修改.config文件的话  怎么修改 加哪几个？
