### ISSUE TITLE
无法使用Synology Drive Client的Windows客户端访问Drive Server

### ISSUE THREAD

**Issue by zhouzh2** [linkease/ddnsto-openwrt#8]
#设置：
应用程序访问规则中打开了drive全部的访问权限，自定义端口10002、10003。关闭客户端防火墙。
#现象：
内网使用drive client访问内网群晖IP可以建立连接。
DDNSto设置成功
外围可以访问映射的dsm、drive别名或端口均成功。
iOS客户端（drive、ds file）设置映射的域名为服务端口，可以成功登陆。
**然而**，windows client无论服务器地址设置为dsm、https、http端口都报无法连接。
请问后续应该如何调试？

**Comment by zhouzh2** [comment]
问题已解决，是由于移动版app使用的http80端口，而桌面版用的是tcp6690端口，ddnsto并不支持tcp打洞，已另外寻找方式解决。

**Comment by hexarzhang** [comment]
请问DDNSTO是怎么解决桌面连接Synology Drive的？
